spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_AUTH_SOURCE}
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

history:
  scheduler:
    occurrence: "0 0 1 * * *"   #every day at 01:00 AM

scheduling:
  enabled: true

auth:
  jwt:
    access-expiration-sec: 900  # 15 * 60
    refresh-expiration-sec: 604800   # 7 * 24 * 60 * 60
    secret: ${JWT_SECRET}
    issuer: meal-planner-backend