#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: mealplanner

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27018/mealplanner
#      database: mealplanner

auth:
  jwt:
    expiration-days: 30
    secret: ${JWT_SECRET}
    issuer: meal-planner-backend