#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: mealplanner

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27018/mealplanner
#      database: mealplanner

history:
  scheduler:
#    occurrence: "0 0 1 * * *"   #every day at 01:00 AM
    occurrence: "0 * * ? * *"   #every minute
#    occurrence: "0 */5 * ? * *"   #every 5 minutes

scheduling:
#  enabled: true
  enabled: false

auth:
  jwt:
#    access-expiration-min: 1
    access-expiration-min: 310
#    refresh-expiration-plans: 7
    refresh-expiration-days: 5
    secret: ${JWT_SECRET}
    issuer: meal-planner-backend