#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: mealplanner

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27018/mealplanner
#      database: mealplanner

auth:
  jwt:
#    access-expiration-min: 1
    access-expiration-min: 30
#    refresh-expiration-days: 7
    refresh-expiration-days: 5
    secret: ${JWT_SECRET}
    issuer: meal-planner-backend
