spring:
  data:
    mongodb:
#      uri: mongodb://admin:admin@localhost:27018/mealplanner?authSource=admin
      uri: mongodb://admin:admin@localhost:27018/mealplanner

history:
  scheduler:
    occurrence: "0 * * ? * *"   #every minute
#    occurrence: "0 */5 * ? * *"   #every 5 minutes

scheduling:
  enabled: false

auth:
  jwt:
#    access-expiration-sec: 5    # 5
#    refresh-expiration-sec: 60  # 1 * 60
    access-expiration-sec: 1800    # 30min * 60s
    refresh-expiration-sec: 86400  # 24h * 60min * 60s