auth:
  jwt:
    access-expiration-sec: 900  # 15 * 60
    refresh-expiration-sec: 604800   # 7 * 24 * 60 * 60
    secret: secret
    issuer: meal-planner-backend

history:
  scheduler:
    occurrence: "*/2 * * * * *"    #every 2 seconds

scheduling:
  enabled: false